[package]
name = "whitebox-tools"
version = "0.1.1"
authors = ["John Lindsay <jlindsay@uoguelph.ca>"]
description = "Library for analyzing geospatial data."
keywords = ["geospatial", "GIS", "geomatics", "lidar", "spatial analysis"]
readme = "README.md"
# repository = "https://github.com/jblindsay/libgeospatial-rs"
# documentation = "http://www.uoguelph.ca/~hydrogeo/software.shtml"
license = "MIT"

[lib]
name = "whitebox_tools"
# crate-type = ["dylib"]
crate-type = ["rlib"]

[dependencies]
# libc = "^0.2.19"
time = "^0.1.35"
kdtree = "^0.3.1"
nalgebra = "^0.10.1"
rand = ">=0.3.15"
# byteorder = "^0.5"
byteorder = "^1.0.0"
num_cpus = "^1.2.1"
rayon = "^0.6.0"
